name: New translation language for the Organized app
description: Request the addition of a new language to the list of languages on Crowdin
labels: [i18n]
body:
  - type: markdown
    attributes:
      value: |
        Add an issue title with this format: [Language] - New Language Request
  - type: textarea
    attributes:
      label: 'Enter which type of translation you will made (ui/source/ui&source):'
      placeholder: |
        Type (ui/source,/ui&source)
    validations:
      required: true
